-- SQL Script to safely convert FLOAT to DECIMAL(15,2) in PostgreSQL

ALTER TABLE "Customers" 
  ALTER COLUMN "creditLimit" TYPE NUMERIC(15,2),
  ALTER COLUMN "openingBalance" TYPE NUMERIC(15,2),
  ALTER COLUMN "balance" TYPE NUMERIC(15,2),
  ALTER COLUMN "totalPurchased" TYPE NUMERIC(15,2),
  ALTER COLUMN "totalPaid" TYPE NUMERIC(15,2);

ALTER TABLE "Suppliers" 
  ALTER COLUMN "creditLimit" TYPE NUMERIC(15,2),
  ALTER COLUMN "openingBalance" TYPE NUMERIC(15,2),
  ALTER COLUMN "balance" TYPE NUMERIC(15,2);

ALTER TABLE "Items" 
  ALTER COLUMN "mrp" TYPE NUMERIC(15,2),
  ALTER COLUMN "selling_price" TYPE NUMERIC(15,2),
  ALTER COLUMN "cost_price" TYPE NUMERIC(15,2);

ALTER TABLE "Bills" 
  ALTER COLUMN "subtotal" TYPE NUMERIC(15,2),
  ALTER COLUMN "gstAmount" TYPE NUMERIC(15,2),
  ALTER COLUMN "discount" TYPE NUMERIC(15,2),
  ALTER COLUMN "total" TYPE NUMERIC(15,2),
  ALTER COLUMN "cgstAmount" TYPE NUMERIC(15,2),
  ALTER COLUMN "sgstAmount" TYPE NUMERIC(15,2),
  ALTER COLUMN "igstAmount" TYPE NUMERIC(15,2),
  ALTER COLUMN "cessAmount" TYPE NUMERIC(15,2);

ALTER TABLE "PurchaseOrders" 
  ALTER COLUMN "subtotal" TYPE NUMERIC(15,2),
  ALTER COLUMN "gstAmount" TYPE NUMERIC(15,2),
  ALTER COLUMN "discount" TYPE NUMERIC(15,2),
  ALTER COLUMN "total" TYPE NUMERIC(15,2),
  ALTER COLUMN "amountPaid" TYPE NUMERIC(15,2),
  ALTER COLUMN "balanceDue" TYPE NUMERIC(15,2),
  ALTER COLUMN "autoScore" TYPE NUMERIC(15,2),
  ALTER COLUMN "cgstAmount" TYPE NUMERIC(15,2),
  ALTER COLUMN "sgstAmount" TYPE NUMERIC(15,2),
  ALTER COLUMN "igstAmount" TYPE NUMERIC(15,2),
  ALTER COLUMN "cessAmount" TYPE NUMERIC(15,2);

ALTER TABLE "Payments" 
  ALTER COLUMN "amount" TYPE NUMERIC(15,2);

ALTER TABLE "Expenses" 
  ALTER COLUMN "amount" TYPE NUMERIC(15,2);

-- Also add deletedAt for paranoid soft deletes
ALTER TABLE "Customers" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "Suppliers" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "Items" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "Bills" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "PurchaseOrders" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE;
