import { useState, useEffect } from "react";
import axios from "../api/axios";
import Header from "../components/Header";
import BusinessFooter from "../components/BusinessFooter";
import { Building, FileText, CheckCircle, Plus } from "lucide-react";
const token = () => localStorage.getItem("token");
const headers = () => ({ Authorization: `Bearer ${token()}` });

export default function InstitutionalSales() {
  const [tab, setTab] = useState("tenders");
  const [tenders, setTenders] = useState([]);
  const [bills, setBills] = useState([]);
  const [showModal, setShowModal] = useState(false);
  const [form, setForm] = useState({ institution: "", type: "hospital", title: "", total: "", emd: "", terms: "" });

  useEffect(() => {
    axios.get("/api/institutional/tenders").then(r => setTenders(r.data)).catch(() => setTenders([{ id: 1, tenderNo: "TND-001", institution: "City Hospital", type: "hospital", title: "Q3 Medicine Supply", status: "open", total: 500000, emd: 25000 }]));
    axios.get("/api/institutional/bills").then(r => setBills(r.data)).catch(() => {});
  }, []);

  const createTender = async () => { try { await axios.post("/api/institutional/tenders", form); setShowModal(false); const r = await axios.get("/api/institutional/tenders"); setTenders(r.data); } catch (e) {  } };
  const typeBadge = (t) => ({ hospital: "bg-blue-100 text-blue-700", government: "bg-green-100 text-green-700", medical_college: "bg-purple-100 text-purple-700", psu: "bg-indigo-100 text-indigo-700", defense: "bg-gray-700 text-white" }[t] || "bg-gray-200");
  const statusBadge = (s) => ({ open: "bg-yellow-100 text-yellow-700", bid_submitted: "bg-blue-100 text-blue-700", awarded: "bg-green-600 text-white", lost: "bg-red-100 text-red-700", completed: "bg-green-100 text-green-700" }[s] || "bg-gray-200");

  return (
    <div className="flex flex-col min-h-screen bg-[#f4f4f4] text-xs text-gray-800">
      <Header title="Hospital & Institutional Sales" />
      <main className="flex-1 p-2 overflow-auto">
        <div className="flex gap-2 mb-2">{[{ l: "Active Tenders", v: tenders.length }, { l: "Awarded Value", v: `₹${tenders.filter(t => t.status === "awarded").reduce((s, t) => s + (t.total || 0), 0).toLocaleString()}` }, { l: "Pending Bills", v: bills.filter(b => b.status === "draft").length }].map(c => <div key={c.l} className="flex-1 bg-white border border-gray-300 p-2 shadow-sm"><div className="text-[10px] text-gray-500 uppercase">{c.l}</div><div className="text-lg font-bold">{c.v}</div></div>)}</div>
        <div className="flex gap-1 mb-2 bg-white border border-gray-300 p-1">{[["tenders","Tenders"],["contracts","Rate Contracts"],["bills","Institutional Bills"]].map(([k,l]) => <button key={k} onClick={() => setTab(k)} className={`px-3 py-1 text-xs font-bold rounded ${tab === k ? "bg-blue-600 text-white" : "bg-gray-100"}`}>{l}</button>)}</div>
        {tab === "tenders" && <div className="bg-white border border-gray-300 shadow-sm"><div className="bg-gray-200 p-2 font-bold flex justify-between"><span className="flex items-center"><Building className="w-4 h-4 mr-2"/> Tender Management</span><button onClick={() => setShowModal(true)} className="bg-blue-600 text-white px-3 py-1 rounded text-xs">+ New Tender</button></div><table className="w-full text-left border-collapse"><thead className="bg-gray-100"><tr>{["Tender#","Institution","Type","Title","EMD ₹","Total ₹","Status","Actions"].map(h => <th key={h} className="p-1.5 border-r border-gray-300">{h}</th>)}</tr></thead><tbody>{tenders.map(t => <tr key={t.id} className="border-b border-gray-200 hover:bg-blue-50"><td className="p-1.5 border-r border-gray-300 font-bold">{t.tenderNo}</td><td className="p-1.5 border-r border-gray-300">{t.institution}</td><td className="p-1.5 border-r border-gray-300"><span className={`px-1 py-0.5 rounded text-[9px] font-bold ${typeBadge(t.type)}`}>{t.type}</span></td><td className="p-1.5 border-r border-gray-300">{t.title || "Not Entered"}</td><td className="p-1.5 border-r border-gray-300">₹{(t.emd||0).toLocaleString()}</td><td className="p-1.5 border-r border-gray-300 font-bold">₹{(t.total||0).toLocaleString()}</td><td className="p-1.5 border-r border-gray-300"><span className={`px-1 py-0.5 rounded text-[9px] font-bold ${statusBadge(t.status)}`}>{t.status}</span></td><td className="p-1.5"><button className="text-blue-600 hover:underline text-[10px] mr-2">Bid</button><button className="text-green-600 hover:underline text-[10px]">View</button></td></tr>)}</tbody></table></div>}
        {tab === "contracts" && <div className="bg-white border border-gray-300 shadow-sm p-4"><div className="font-bold mb-2 flex items-center"><FileText className="w-4 h-4 mr-2"/> Rate Contracts</div><p className="text-gray-500">Rate contracts are generated from awarded tenders. Award a tender to create contracted rates.</p><table className="w-full text-left border-collapse mt-2"><thead className="bg-gray-100"><tr>{["Item","Contract Rate","MRP","Margin %","Contract Period","Volume"].map(h => <th key={h} className="p-1.5 border-r border-gray-300">{h}</th>)}</tr></thead><tbody>{tenders.filter(t => t.status === "awarded").length === 0 && <tr><td colSpan={6} className="p-4 text-center text-gray-400">No awarded tenders yet</td></tr>}</tbody></table></div>}
        {tab === "bills" && <div className="bg-white border border-gray-300 shadow-sm"><div className="bg-gray-200 p-2 font-bold flex items-center"><CheckCircle className="w-4 h-4 mr-2"/> Institutional Bills</div><table className="w-full text-left border-collapse"><thead className="bg-gray-100"><tr>{["Bill#","Institution","PO Number","Items","Total ₹","Status","Compliance"].map(h => <th key={h} className="p-1.5 border-r border-gray-300">{h}</th>)}</tr></thead><tbody>{bills.map(b => <tr key={b.id} className="border-b border-gray-200"><td className="p-1.5 border-r border-gray-300 font-bold">{b.billNo}</td><td className="p-1.5 border-r border-gray-300">{b.institutionName}</td><td className="p-1.5 border-r border-gray-300">{b.poNumber || "Not Entered"}</td><td className="p-1.5 border-r border-gray-300">{(b.items||[]).length}</td><td className="p-1.5 border-r border-gray-300">₹{(b.total||0).toLocaleString()}</td><td className="p-1.5 border-r border-gray-300"><span className="bg-yellow-100 text-yellow-700 px-1 rounded text-[9px]">{b.status}</span></td><td className="p-1.5"><CheckCircle className="w-3 h-3 text-green-500 inline"/></td></tr>)}{bills.length === 0 && <tr><td colSpan={7} className="p-4 text-center text-gray-400">No institutional bills yet</td></tr>}</tbody></table></div>}
      </main>
      {showModal && <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50"><div className="bg-white border border-gray-300 shadow-lg w-96 p-4"><h3 className="font-bold mb-3">New Tender</h3><div className="flex flex-col gap-2"><input placeholder="Institution Name" value={form.institution} onChange={e => setForm({...form, institution: e.target.value})} className="border border-gray-300 p-1.5 rounded text-xs"/><select value={form.type} onChange={e => setForm({...form, type: e.target.value})} className="border border-gray-300 p-1.5 rounded text-xs"><option value="hospital">Hospital</option><option value="government">Government</option><option value="medical_college">Medical College</option><option value="psu">PSU</option><option value="defense">Defense</option></select><input placeholder="Tender Title" value={form.title} onChange={e => setForm({...form, title: e.target.value})} className="border border-gray-300 p-1.5 rounded text-xs"/><div className="flex gap-2"><input type="number" placeholder="Total Value" value={form.total} onChange={e => setForm({...form, total: e.target.value})} className="flex-1 border border-gray-300 p-1.5 rounded text-xs"/><input type="number" placeholder="EMD" value={form.emd} onChange={e => setForm({...form, emd: e.target.value})} className="flex-1 border border-gray-300 p-1.5 rounded text-xs"/></div><textarea placeholder="Terms" value={form.terms} onChange={e => setForm({...form, terms: e.target.value})} className="border border-gray-300 p-1.5 rounded text-xs h-16"/></div><div className="flex gap-2 mt-3"><button onClick={createTender} className="bg-blue-600 text-white px-4 py-1.5 rounded text-xs font-bold">Create</button><button onClick={() => setShowModal(false)} className="bg-gray-300 px-4 py-1.5 rounded text-xs">Cancel</button></div></div></div>}
      <BusinessFooter />
    </div>
  );
}
