import { useState, useEffect } from "react";
import axios from "../api/axios";
import Header from "../components/Header";
import BusinessFooter from "../components/BusinessFooter";
import { Puzzle, Globe, Key, Power, Settings, Trash2, Eye, EyeOff, Copy } from "lucide-react";
const token = () => localStorage.getItem("token");
const headers = () => ({ Authorization: `Bearer ${token()}` });

const EVENTS = ["invoice_created", "payment_received", "stock_updated", "order_placed", "purchase_created", "expiry_approaching"];

export default function PlatformAdmin() {
  const [tab, setTab] = useState("plugins");
  const [plugins, setPlugins] = useState([]);
  const [webhooks, setWebhooks] = useState([]);
  const [apiKeys, setApiKeys] = useState([]);
  const [showModal, setShowModal] = useState(null);
  const [form, setForm] = useState({});
  const [showKeys, setShowKeys] = useState({});
  const [newKey, setNewKey] = useState(null);

  useEffect(() => {
    axios.get("/api/plugins").then(r => setPlugins(r.data)).catch(() => {});
    axios.get("/api/webhooks").then(r => setWebhooks(r.data)).catch(() => {});
    axios.get("/api/api-keys").then(r => setApiKeys(r.data)).catch(() => {});
  }, []);

  const togglePlugin = async (id) => { try { await axios.post(`/api/plugins/${id}/toggle`, {}); setPlugins(plugins.map(p => p.id === id ? { ...p, isActive: !p.isActive } : p)); } catch (e) {} };
  const deletePlugin = async (id) => { if (!confirm("Uninstall?")) return; try { await axios.delete(`/api/plugins/${id}`); setPlugins(plugins.filter(p => p.id !== id)); } catch (e) {} };
  const installPlugin = async () => { try { const r = await axios.post("/api/plugins/install", form); setPlugins([...plugins, r.data]); setShowModal(null); } catch (e) {  } };
  const addWebhook = async () => { try { const r = await axios.post("/api/webhooks", form); setWebhooks([...webhooks, r.data]); setShowModal(null); } catch (e) {  } };
  const deleteWebhook = async (id) => { try { await axios.delete(`/api/webhooks/${id}`); setWebhooks(webhooks.filter(w => w.id !== id)); } catch (e) {} };
  const generateKey = async () => { try { const r = await axios.post("/api/api-keys", form); setApiKeys([...apiKeys, r.data]); setNewKey(r.data.key); setShowModal(null); } catch (e) {  } };
  const revokeKey = async (id) => { try { await axios.delete(`/api/api-keys/${id}`); setApiKeys(apiKeys.filter(k => k.id !== id)); } catch (e) {} };
  const maskKey = (key) => key ? `${key.substring(0, 8)}...${key.substring(key.length - 4)}` : "";

  return (
    <div className="flex flex-col min-h-screen bg-[#f4f4f4] text-xs text-gray-800">
      <Header title="Platform Administration" />
      <main className="flex-1 p-2 overflow-auto flex flex-col gap-2">
        <div className="flex gap-1 bg-white border border-gray-300 p-1">{[["plugins","Plugins","Puzzle"],["webhooks","Webhooks","Globe"],["apikeys","API Keys","Key"]].map(([k,l]) => <button key={k} onClick={() => setTab(k)} className={`px-3 py-1 text-xs font-bold rounded flex items-center gap-1 ${tab === k ? "bg-blue-600 text-white" : "bg-gray-100"}`}>{l}</button>)}</div>
        {newKey && <div className="bg-green-50 border border-green-300 p-3 rounded flex justify-between items-center"><div><div className="font-bold text-green-700">API Key Generated!</div><div className="font-mono text-sm mt-1">{newKey}</div><div className="text-[9px] text-green-600 mt-0.5">Copy this key now. It won't be shown again.</div></div><button onClick={() => { navigator.clipboard.writeText(newKey); setNewKey(null); }} className="bg-green-600 text-white px-3 py-1.5 rounded text-xs font-bold flex items-center"><Copy className="w-3 h-3 mr-1"/> Copy & Close</button></div>}
        {tab === "plugins" && <div><div className="flex justify-between items-center mb-2"><span className="font-bold text-sm flex items-center"><Puzzle className="w-4 h-4 mr-2"/> Installed Plugins</span><button onClick={() => { setShowModal("plugin"); setForm({ name: "", version: "1.0.0", author: "", description: "" }); }} className="bg-blue-600 text-white px-3 py-1 rounded text-xs">+ Install Plugin</button></div>
          <div className="grid grid-cols-2 gap-2">{plugins.map(p => <div key={p.id} className="bg-white border border-gray-300 shadow-sm p-3 hover:shadow-md transition-shadow"><div className="flex justify-between items-start"><div><div className="font-bold text-sm">{p.name}</div><div className="text-[10px] text-gray-500">v{p.version} by {p.author || "Unknown"}</div></div><button onClick={() => togglePlugin(p.id)} className={`w-10 h-5 rounded-full relative ${p.isActive ? "bg-green-500" : "bg-gray-300"}`}><span className={`absolute top-0.5 w-4 h-4 rounded-full bg-white transition-all ${p.isActive ? "right-0.5" : "left-0.5"}`}></span></button></div><div className="text-[10px] text-gray-600 mt-1">{p.description || "No description"}</div><div className="flex gap-1 mt-2"><span className={`px-1 py-0.5 rounded text-[8px] font-bold ${p.isActive ? "bg-green-100 text-green-700" : "bg-gray-200 text-gray-600"}`}>{p.isActive ? "Active" : "Inactive"}</span>{(p.hooks || []).map((h, i) => <span key={i} className="bg-blue-100 text-blue-700 px-1 py-0.5 rounded text-[8px]">{h}</span>)}</div><div className="flex gap-1 mt-2"><button className="bg-gray-100 px-2 py-0.5 rounded text-[10px] flex items-center"><Settings className="w-3 h-3 mr-0.5"/> Config</button><button onClick={() => deletePlugin(p.id)} className="bg-red-100 text-red-600 px-2 py-0.5 rounded text-[10px] flex items-center"><Trash2 className="w-3 h-3 mr-0.5"/> Uninstall</button></div></div>)}</div>
        </div>}
        {tab === "webhooks" && <div className="bg-white border border-gray-300 shadow-sm"><div className="bg-gray-200 p-2 font-bold flex justify-between"><span className="flex items-center"><Globe className="w-4 h-4 mr-2"/> Registered Webhooks</span><button onClick={() => { setShowModal("webhook"); setForm({ name: "", url: "", events: [] }); }} className="bg-blue-600 text-white px-3 py-1 rounded text-xs">+ Register</button></div><table className="w-full text-left border-collapse"><thead className="bg-gray-100"><tr>{["Name","URL","Events","Last Triggered","Failures","Active",""].map(h => <th key={h} className="p-1.5 border-r border-gray-300">{h}</th>)}</tr></thead><tbody>{webhooks.map(w => <tr key={w.id} className="border-b border-gray-200"><td className="p-1.5 border-r border-gray-300 font-bold">{w.name || "Not Entered"}</td><td className="p-1.5 border-r border-gray-300 font-mono text-[9px]">{w.url}</td><td className="p-1.5 border-r border-gray-300">{(w.events || []).map((e, i) => <span key={i} className="bg-blue-100 text-blue-700 px-1 rounded text-[8px] mr-0.5">{e}</span>)}</td><td className="p-1.5 border-r border-gray-300 text-[9px]">{w.lastTriggered ? new Date(w.lastTriggered).toLocaleString() : "Never"}</td><td className="p-1.5 border-r border-gray-300">{w.failureCount || 0}</td><td className="p-1.5 border-r border-gray-300">{w.isActive ? "✅" : "❌"}</td><td className="p-1.5"><button onClick={() => deleteWebhook(w.id)} className="text-red-600"><Trash2 className="w-3 h-3"/></button></td></tr>)}{webhooks.length === 0 && <tr><td colSpan={7} className="p-4 text-center text-gray-400">No webhooks registered</td></tr>}</tbody></table></div>}
        {tab === "apikeys" && <div className="bg-white border border-gray-300 shadow-sm"><div className="bg-gray-200 p-2 font-bold flex justify-between"><span className="flex items-center"><Key className="w-4 h-4 mr-2"/> API Keys</span><button onClick={() => { setShowModal("apikey"); setForm({ name: "", permissions: ["read"], rateLimit: 60 }); }} className="bg-blue-600 text-white px-3 py-1 rounded text-xs">+ Generate</button></div><table className="w-full text-left border-collapse"><thead className="bg-gray-100"><tr>{["Name","Key","Permissions","Rate Limit","Last Used","Active",""].map(h => <th key={h} className="p-1.5 border-r border-gray-300">{h}</th>)}</tr></thead><tbody>{apiKeys.map(k => <tr key={k.id} className="border-b border-gray-200"><td className="p-1.5 border-r border-gray-300 font-bold">{k.name}</td><td className="p-1.5 border-r border-gray-300 font-mono text-[9px]"><span>{showKeys[k.id] ? k.key : maskKey(k.key)}</span><button onClick={() => setShowKeys({...showKeys, [k.id]: !showKeys[k.id]})} className="ml-1 text-gray-400">{showKeys[k.id] ? <EyeOff className="w-3 h-3 inline"/> : <Eye className="w-3 h-3 inline"/>}</button></td><td className="p-1.5 border-r border-gray-300">{(k.permissions || []).map((p, i) => <span key={i} className="bg-green-100 text-green-700 px-1 rounded text-[8px] mr-0.5">{p}</span>)}</td><td className="p-1.5 border-r border-gray-300">{k.rateLimit}/min</td><td className="p-1.5 border-r border-gray-300 text-[9px]">{k.lastUsed ? new Date(k.lastUsed).toLocaleString() : "Never"}</td><td className="p-1.5 border-r border-gray-300">{k.isActive ? "✅" : "❌"}</td><td className="p-1.5"><button onClick={() => revokeKey(k.id)} className="text-red-600 text-[10px]">Revoke</button></td></tr>)}{apiKeys.length === 0 && <tr><td colSpan={7} className="p-4 text-center text-gray-400">No API keys generated</td></tr>}</tbody></table></div>}
      </main>
      {showModal === "plugin" && <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50"><div className="bg-white border border-gray-300 shadow-lg w-96 p-4"><h3 className="font-bold mb-3">Install Plugin</h3><div className="flex flex-col gap-2"><input placeholder="Plugin Name" value={form.name} onChange={e => setForm({...form, name: e.target.value})} className="border border-gray-300 p-1.5 rounded text-xs"/><input placeholder="Version" value={form.version} onChange={e => setForm({...form, version: e.target.value})} className="border border-gray-300 p-1.5 rounded text-xs"/><input placeholder="Author" value={form.author} onChange={e => setForm({...form, author: e.target.value})} className="border border-gray-300 p-1.5 rounded text-xs"/><textarea placeholder="Description" value={form.description} onChange={e => setForm({...form, description: e.target.value})} className="border border-gray-300 p-1.5 rounded text-xs h-16"/></div><div className="flex gap-2 mt-3"><button onClick={installPlugin} className="bg-blue-600 text-white px-4 py-1.5 rounded text-xs font-bold">Install</button><button onClick={() => setShowModal(null)} className="bg-gray-300 px-4 py-1.5 rounded text-xs">Cancel</button></div></div></div>}
      {showModal === "webhook" && <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50"><div className="bg-white border border-gray-300 shadow-lg w-96 p-4"><h3 className="font-bold mb-3">Register Webhook</h3><div className="flex flex-col gap-2"><input placeholder="Name" value={form.name} onChange={e => setForm({...form, name: e.target.value})} className="border border-gray-300 p-1.5 rounded text-xs"/><input placeholder="URL (https://...)" value={form.url} onChange={e => setForm({...form, url: e.target.value})} className="border border-gray-300 p-1.5 rounded text-xs"/><label className="text-[10px] font-bold text-gray-500 uppercase">Events:</label><div className="flex flex-wrap gap-1">{EVENTS.map(ev => <label key={ev} className="flex items-center gap-1 text-[10px]"><input type="checkbox" checked={(form.events||[]).includes(ev)} onChange={e => { const evts = form.events || []; setForm({...form, events: e.target.checked ? [...evts, ev] : evts.filter(x => x !== ev)}); }}/>{ev}</label>)}</div></div><div className="flex gap-2 mt-3"><button onClick={addWebhook} className="bg-blue-600 text-white px-4 py-1.5 rounded text-xs font-bold">Register</button><button onClick={() => setShowModal(null)} className="bg-gray-300 px-4 py-1.5 rounded text-xs">Cancel</button></div></div></div>}
      {showModal === "apikey" && <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50"><div className="bg-white border border-gray-300 shadow-lg w-96 p-4"><h3 className="font-bold mb-3">Generate API Key</h3><div className="flex flex-col gap-2"><input placeholder="Key Name" value={form.name} onChange={e => setForm({...form, name: e.target.value})} className="border border-gray-300 p-1.5 rounded text-xs"/><label className="text-[10px] font-bold text-gray-500 uppercase">Permissions:</label><div className="flex flex-wrap gap-1">{["read", "write", "billing", "inventory", "reports"].map(p => <label key={p} className="flex items-center gap-1 text-[10px]"><input type="checkbox" checked={(form.permissions||[]).includes(p)} onChange={e => { const perms = form.permissions || []; setForm({...form, permissions: e.target.checked ? [...perms, p] : perms.filter(x => x !== p)}); }}/>{p}</label>)}</div><input type="number" placeholder="Rate Limit (req/min)" value={form.rateLimit} onChange={e => setForm({...form, rateLimit: Number(e.target.value)})} className="border border-gray-300 p-1.5 rounded text-xs"/></div><div className="flex gap-2 mt-3"><button onClick={generateKey} className="bg-blue-600 text-white px-4 py-1.5 rounded text-xs font-bold">Generate</button><button onClick={() => setShowModal(null)} className="bg-gray-300 px-4 py-1.5 rounded text-xs">Cancel</button></div></div></div>}
      <BusinessFooter />
    </div>
  );
}
