import { useState, useEffect } from "react";
import axios from "axios";
import Header from "../components/Header";
import BusinessFooter from "../components/BusinessFooter";
import { BarChart3, Gift, Package, TrendingUp, TrendingDown } from "lucide-react";
const token = () => localStorage.getItem("token");
const headers = () => ({ Authorization: `Bearer ${token()}` });

export default function SupplierPortal() {
  const [tab, setTab] = useState("sellthrough");
  const [sellThrough, setSellThrough] = useState([]);
  const [schemes, setSchemes] = useState([]);
  const [showModal, setShowModal] = useState(false);
  const [form, setForm] = useState({ schemeName: "", type: "buy_get_free", minQty: "", freeQty: "", discountPercent: "", validFrom: "", validTo: "", supplierName: "Self", supplierId: 1 });

  useEffect(() => {
    axios.get("/api/marketplace/supplier/sell-through", { headers: headers() }).then(r => setSellThrough(r.data)).catch(() => setSellThrough([{ id: 1, name: "Dolo 650", stockAtDistributor: 200, sold30d: 150, velocity: 5.0, trend: "up" }]));
    axios.get("/api/marketplace/schemes", { headers: headers() }).then(r => setSchemes(r.data)).catch(() => {});
  }, []);

  const pushScheme = async () => { try { await axios.post("/api/marketplace/supplier/push-scheme", form, { headers: headers() }); setShowModal(false); const r = await axios.get("/api/marketplace/schemes", { headers: headers() }); setSchemes(r.data); } catch (e) { alert(e.message); } };

  return (
    <div className="flex flex-col min-h-screen bg-[#f4f4f4] text-xs text-gray-800">
      <Header title="Supplier Portal" />
      <main className="flex-1 p-2 overflow-auto">
        <div className="flex gap-1 mb-2 bg-white border border-gray-300 p-1">{[["sellthrough","Sell-Through Analytics"],["schemes","Push Schemes"],["inventory","Inventory Monitor"]].map(([k,l]) => <button key={k} onClick={() => setTab(k)} className={`px-3 py-1 text-xs font-bold rounded ${tab === k ? "bg-blue-600 text-white" : "bg-gray-100"}`}>{l}</button>)}</div>
        {tab === "sellthrough" && <div className="bg-white border border-gray-300 shadow-sm"><div className="bg-gray-200 p-2 font-bold flex items-center"><BarChart3 className="w-4 h-4 mr-2"/> Product Sell-Through</div><table className="w-full text-left border-collapse"><thead className="bg-gray-100"><tr>{["Product","Company","Stock","Sold (30d)","Velocity","Trend"].map(h => <th key={h} className="p-1.5 border-r border-gray-300">{h}</th>)}</tr></thead><tbody>{sellThrough.map(s => <tr key={s.id} className="border-b border-gray-200 hover:bg-blue-50"><td className="p-1.5 border-r border-gray-300 font-bold">{s.name}</td><td className="p-1.5 border-r border-gray-300">{s.company}</td><td className="p-1.5 border-r border-gray-300">{s.stockAtDistributor}</td><td className="p-1.5 border-r border-gray-300 font-bold">{s.sold30d}</td><td className="p-1.5 border-r border-gray-300">{s.velocity}/day</td><td className="p-1.5">{s.trend === "up" ? <TrendingUp className="w-4 h-4 text-green-600"/> : <TrendingDown className="w-4 h-4 text-red-600"/>}</td></tr>)}</tbody></table></div>}
        {tab === "schemes" && <div className="bg-white border border-gray-300 shadow-sm"><div className="bg-gray-200 p-2 font-bold flex justify-between items-center"><span className="flex items-center"><Gift className="w-4 h-4 mr-2"/> Active Schemes</span><button onClick={() => setShowModal(true)} className="bg-blue-600 text-white px-3 py-1 rounded text-xs">+ Push Scheme</button></div><table className="w-full text-left border-collapse"><thead className="bg-gray-100"><tr>{["Scheme","Type","Min Qty","Free/Disc","Valid From","Valid To","Active"].map(h => <th key={h} className="p-1.5 border-r border-gray-300">{h}</th>)}</tr></thead><tbody>{schemes.map(s => <tr key={s.id} className="border-b border-gray-200"><td className="p-1.5 border-r border-gray-300 font-bold">{s.schemeName}</td><td className="p-1.5 border-r border-gray-300"><span className="bg-purple-100 text-purple-700 px-1 rounded text-[9px] font-bold">{s.type}</span></td><td className="p-1.5 border-r border-gray-300">{s.minQty}</td><td className="p-1.5 border-r border-gray-300">{s.type === "buy_get_free" ? `${s.freeQty} free` : `${s.discountPercent}%`}</td><td className="p-1.5 border-r border-gray-300">{s.validFrom || "Not Entered"}</td><td className="p-1.5 border-r border-gray-300">{s.validTo || "Not Entered"}</td><td className="p-1.5">{s.isActive ? "✅" : "❌"}</td></tr>)}</tbody></table></div>}
        {tab === "inventory" && <div className="bg-white border border-gray-300 shadow-sm"><div className="bg-gray-200 p-2 font-bold flex items-center"><Package className="w-4 h-4 mr-2"/> Inventory at Distributor</div><table className="w-full text-left border-collapse"><thead className="bg-gray-100"><tr>{["Product","Stock Qty","Velocity","Days of Stock","Status"].map(h => <th key={h} className="p-1.5 border-r border-gray-300">{h}</th>)}</tr></thead><tbody>{sellThrough.map(s => { const dos = s.velocity > 0 ? Math.round(s.stockAtDistributor / s.velocity) : 999; return <tr key={s.id} className="border-b border-gray-200"><td className="p-1.5 border-r border-gray-300 font-bold">{s.name}</td><td className="p-1.5 border-r border-gray-300">{s.stockAtDistributor}</td><td className="p-1.5 border-r border-gray-300">{s.velocity}/day</td><td className="p-1.5 border-r border-gray-300 font-bold">{dos}d</td><td className="p-1.5"><span className={`px-1 py-0.5 rounded text-[9px] font-bold ${dos < 7 ? "bg-red-100 text-red-700" : dos < 15 ? "bg-yellow-100 text-yellow-700" : "bg-green-100 text-green-700"}`}>{dos < 7 ? "Critical" : dos < 15 ? "Low" : "OK"}</span></td></tr>; })}</tbody></table></div>}
      </main>
      {showModal && <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50"><div className="bg-white border border-gray-300 shadow-lg w-96 p-4"><h3 className="font-bold mb-3">Push New Scheme</h3><div className="flex flex-col gap-2"><input placeholder="Scheme Name" value={form.schemeName} onChange={e => setForm({...form, schemeName: e.target.value})} className="border border-gray-300 p-1.5 rounded text-xs"/><select value={form.type} onChange={e => setForm({...form, type: e.target.value})} className="border border-gray-300 p-1.5 rounded text-xs"><option value="buy_get_free">Buy X Get Y Free</option><option value="flat_discount">Flat Discount</option><option value="volume">Volume Discount</option></select><input type="number" placeholder="Min Qty" value={form.minQty} onChange={e => setForm({...form, minQty: e.target.value})} className="border border-gray-300 p-1.5 rounded text-xs"/>{form.type === "buy_get_free" ? <input type="number" placeholder="Free Qty" value={form.freeQty} onChange={e => setForm({...form, freeQty: e.target.value})} className="border border-gray-300 p-1.5 rounded text-xs"/> : <input type="number" placeholder="Discount %" value={form.discountPercent} onChange={e => setForm({...form, discountPercent: e.target.value})} className="border border-gray-300 p-1.5 rounded text-xs"/>}<div className="flex gap-2"><input type="date" value={form.validFrom} onChange={e => setForm({...form, validFrom: e.target.value})} className="flex-1 border border-gray-300 p-1.5 rounded text-xs"/><input type="date" value={form.validTo} onChange={e => setForm({...form, validTo: e.target.value})} className="flex-1 border border-gray-300 p-1.5 rounded text-xs"/></div></div><div className="flex gap-2 mt-3"><button onClick={pushScheme} className="bg-blue-600 text-white px-4 py-1.5 rounded text-xs font-bold">Push</button><button onClick={() => setShowModal(false)} className="bg-gray-300 px-4 py-1.5 rounded text-xs">Cancel</button></div></div></div>}
      <BusinessFooter />
    </div>
  );
}
